from typing import List, Optional
from .entities import Investigador, Adscripcion

class InvestigadorRepositoryPort:
    def crear(self, investigador: Investigador) -> Investigador: ...
    def actualizar(self, investigador: Investigador) -> None: ...
    def eliminar(self, id_investigador: int) -> None: ...
    def listar(self) -> List[Investigador]: ...
    def obtener(self, id_investigador: int) -> Optional[Investigador]: ...
    def crear_adscripcion(self, adscripcion: Adscripcion) -> Adscripcion: ...
