services:
  web:
    image: docker.io/${DOCKERHUB_USERNAME}/backend-registros-historicos:${APP_TAG:-latest}
    container_name: backend-registros-historicos
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

    pull_policy: always

    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput || true &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
