from typing import Optional, Protocol

class RegistroRepository(Protocol):
    def insertar(self, registro: 'Registro') -> 'Registro': ...
    def actualizar(self, id_registro: int, registro: 'Registro') -> 'Registro': ...
    def habilitar(self, id_registro: int) -> None: ...
    def deshabilitar(self, id_registro: int) -> None: ...
    def listar_por_tipo(self, tipo_registro_param: int, limit: int, offset: int) -> list[dict]: ...
    def contar_por_tipo(self, tipo_registro_param: int) -> int: ...
    def buscar_por_texto(self, tipo_registro_param: int, texto: str, limit: int, offset: int) -> list[dict]: ...
    def contar_por_texto(self, tipo_registro_param: int, texto: str) -> int: ...
    def obtener_por_id(self, id_registro: int) -> Optional[dict]: ...
    def obtener_por_expediente(self, no_expediente: str) -> Optional[dict]: ...