from typing import Protocol

class RegistroRepository(Protocol):
    def insertar(self, registro: 'Registro') -> 'Registro': ...
    def actualizar(self, id_registro: int, registro: 'Registro') -> 'Registro': ...
    def habilitar(self, id_registro: int) -> None: ...
    def deshabilitar(self, id_registro: int) -> None: ...